
local PLUGIN = PLUGIN

PLUGIN.name = "Overwatch Voices"
PLUGIN.author = "Ice Bear#2034"
PLUGIN.description = "Adds all the missing CP voice lines from the HL2 Beta Leak as well as adding in voice lines for Airwatch."
PLUGIN.schema = "HL2 RP"
PLUGIN.license = [[
Copyright 2019 Oscar Detnon

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]]

-- CP Conversation Line Answers (mc1ans)
Schema.voices.Add("Overwatch", "Hm", "Hmph.", "npc/metropolice/mc1ans_hm.wav")
Schema.voices.Add("Overwatch", "Nope", "Nope.", "npc/metropolice/mc1ans_nope.wav")
Schema.voices.Add("Overwatch", "Bellyaching", "Quit your bellyaching.", "npc/metropolice/mc1ans_bellyaching.wav")
Schema.voices.Add("Overwatch", "Believe what you want", "Believe what you want.", "npc/metropolice/mc1ans_believewhatyouwant.wav")
Schema.voices.Add("Overwatch", "Could be", "Eh, could be.", "npc/metropolice/mc1ans_couldbe.wav")
Schema.voices.Add("Overwatch", "Dont be ridiculous", "Don't be ridiculous.", "npc/metropolice/mc1ans_dontberidic.wav")
Schema.voices.Add("Overwatch", "Dont wanna talk", "I don't wanna talk about it.", "npc/metropolice/mc1ans_dontwannatalk.wav")
Schema.voices.Add("Overwatch", "Enough", "That's enough outta you.", "npc/metropolice/mc1ans_enoughouttayou.wav")
Schema.voices.Add("Overwatch", "Fascinating", "Fascinating.", "npc/metropolice/mc1ans_fascinating.wav")
Schema.voices.Add("Overwatch", "Figures", "Figures.", "npc/metropolice/mc1ans_figures.wav")
Schema.voices.Add("Overwatch", "Partner", "I had to get you for a partner.", "npc/metropolice/mc1ans_hadtopartner.wav")
Schema.voices.Add("Overwatch", "Helluva mood", "You're in a helluva mood.", "npc/metropolice/mc1ans_helluvamood.wav")
Schema.voices.Add("Overwatch", "Huh figures", "Huh, figures.", "npc/metropolice/mc1ans_huhfigures.wav")
Schema.voices.Add("Overwatch", "Let me think", "Let me think about that.", "npc/metropolice/mc1ans_letmethink.wav")
Schema.voices.Add("Overwatch", "Might be", "Might be.", "npc/metropolice/mc1ans_mightbe.wav")
Schema.voices.Add("Overwatch", "Might could", "Might could.", "npc/metropolice/mc1ans_mightcould.wav")
Schema.voices.Add("Overwatch", "Rather not talk", "I'd rather not talk about that.", "npc/metropolice/mc1ans_rathernottalk.wav")
Schema.voices.Add("Overwatch", "Rather not think", "I'd rather not think about that.", "npc/metropolice/mc1ans_rathernotthink.wav")
Schema.voices.Add("Overwatch", "Shut up", "Shut up about that.", "npc/metropolice/mc1ans_shutup.wav")
Schema.voices.Add("Overwatch", "Stop whining", "Stop whining.", "npc/metropolice/mc1ans_stopwhining.wav")
Schema.voices.Add("Overwatch", "Theres your problem", "There's your problem right there.", "npc/metropolice/mc1ans_theresyerproblem.wav")
Schema.voices.Add("Overwatch", "Think so", "Think so.", "npc/metropolice/mc1ans_thinkso.wav")
Schema.voices.Add("Overwatch", "Watch your mouth", "Watch your mouth.", "npc/metropolice/mc1ans_watchyermouth.wav")
Schema.voices.Add("Overwatch", "You expect me", "You expect me to believe that?", "npc/metropolice/mc1ans_youexpectme.wav")
Schema.voices.Add("Overwatch", "You really believe", "You really believe that?", "npc/metropolice/mc1ans_youreallybelieve.wav")

-- CP Conversation Line Questions (mc1que)
Schema.voices.Add("Overwatch", "Better things", "I got better things to do.", "npc/metropolice/mc1que_betterthings.wav")
Schema.voices.Add("Overwatch", "Career", "Yep, this was definitely the best career choice I've ever made.", "npc/metropolice/mc1que_career.wav")
Schema.voices.Add("Overwatch", "Enlisting", "So, I'm thinking of enlisting.", "npc/metropolice/mc1que_enlisting.wav")
Schema.voices.Add("Overwatch", "Everything I hoped", "This is everything I hoped it would be.", "npc/metropolice/mc1que_everythingihoped.wav")
Schema.voices.Add("Overwatch", "Feeling good", "I'm feeling pretty good about myself today.", "npc/metropolice/mc1que_feelinggood.wav")
Schema.voices.Add("Overwatch", "Feet killing", "My feet are killing me.", "npc/metropolice/mc1que_feetkillin.wav")
Schema.voices.Add("Overwatch", "Going to hell", "This whole place is going to hell. Well, not this place.", "npc/metropolice/mc1que_goingtohell.wav")
Schema.voices.Add("Overwatch", "Just thought", "I just thought of something. Uh, wait... maybe not.", "npc/metropolice/mc1que_justthought.wav")
Schema.voices.Add("Overwatch", "Kids", "I wouldn't have kids even if they let me.", "npc/metropolice/mc1que_kids.wav")
Schema.voices.Add("Overwatch", "Last job", "Beats the shit out of my last job.", "npc/metropolice/mc1que_lastjob.wav")
Schema.voices.Add("Overwatch", "Pay cut", "What do you bet we get a pay cut?", "npc/metropolice/mc1que_paycut.wav")
Schema.voices.Add("Overwatch", "People suck", "People suck. Well, except for us, I mean.", "npc/metropolice/mc1que_peoplesuck.wav")
Schema.voices.Add("Overwatch", "Perks", "So, you getting the perks they promised you?", "npc/metropolice/mc1que_perks.wav")
Schema.voices.Add("Overwatch", "Raise", "Supposedly, we're getting a raise next week.", "npc/metropolice/mc1que_raise.wav")
Schema.voices.Add("Overwatch", "Stimpatch", "I could use another stimpatch.", "npc/metropolice/mc1que_stimpatch.wav")
Schema.voices.Add("Overwatch", "Stomach", "My stomach is killing me.", "npc/metropolice/mc1que_stomach.wav")
Schema.voices.Add("Overwatch", "Stunsticks", "I hear we're not getting those new stunsticks this year.", "npc/metropolice/mc1que_stunsticks.wav")
Schema.voices.Add("Overwatch", "Ridiculous", "This is ridiculous.", "npc/metropolice/mc1que_thisridiculous.wav")
Schema.voices.Add("Overwatch", "Your wife", "Your wife doesn't like me, does she?", "npc/metropolice/mc1que_yourwife.wav")

-- CP Miscellaneous
Schema.voices.Add("Overwatch", "Heads up", "Heads up!", "npc/metropolice/deploy01.wav")
Schema.voices.Add("Overwatch", "Let them loose", "Let 'em loose!", "npc/metropolice/deploy02.wav")
Schema.voices.Add("Overwatch", "Give chase", "Give chase.", "npc/metropolice/deploy03.wav")
Schema.voices.Add("Overwatch", "Heads", "Heads!", "npc/metropolice/deploy04.wav")
Schema.voices.Add("Overwatch", "Deploying remote", "Deploying remote!", "npc/metropolice/deploy05.wav")
Schema.voices.Add("Overwatch", "Release", "Release!", "npc/metropolice/deploy06.wav")
Schema.voices.Add("Overwatch", "Drop your weapon", "Drop your weapon, get down!", "npc/metropolice/dropweapon.wav")
Schema.voices.Add("Overwatch", "On the ground", "Stay where you are, get on the ground! Do it now!", "npc/metropolice/getonground.wav")
Schema.voices.Add("Overwatch", "Freeze", "Freeze!", "npc/metropolice/freeze.wav")
Schema.voices.Add("Overwatch", "On the ground", "Stay where you are, get on the ground! Do it now!", "npc/metropolice/getonground.wav")
Schema.voices.Add("Overwatch", "Freeze", "Freeze!", "npc/metropolice/freeze.wav")
Schema.voices.Add("Overwatch", "On the ground", "Stay where you are, get on the ground! Do it now!", "npc/metropolice/getonground.wav")
Schema.voices.Add("Overwatch", "Out of there", "Get out of there!", "npc/metropolice/hiding01.wav")
Schema.voices.Add("Overwatch", "No point hiding", "There's no point in hiding.", "npc/metropolice/hiding02.wav")
Schema.voices.Add("Overwatch", "No escape", "You have no chance of escape.", "npc/metropolice/hiding03.wav")
Schema.voices.Add("Overwatch", "Surrounded", "You're surrounded.", "npc/metropolice/hiding04.wav")
Schema.voices.Add("Overwatch", "Covered", "We have you covered.", "npc/metropolice/hiding05.wav")
Schema.voices.Add("Overwatch", "Over there", "Over there!", "npc/metropolice/pointer01.wav")
Schema.voices.Add("Overwatch", "There", "There!", "npc/metropolice/pointer02.wav")
Schema.voices.Add("Overwatch", "Look", "Look!", "npc/metropolice/pointer03.wav")
Schema.voices.Add("Overwatch", "Get away", "Don't let him get away!", "npc/metropolice/pointer04.wav")
Schema.voices.Add("Overwatch", "Getting away", "He's getting away!", "npc/metropolice/pointer06.wav")
Schema.voices.Add("Overwatch", "Got him", "Got him!", "npc/metropolice/shooter01.wav")
Schema.voices.Add("Overwatch", "Have him", "I have him!", "npc/metropolice/shooter02.wav")
Schema.voices.Add("Overwatch", "Hes mine", "He's mine!", "npc/metropolice/shooter03.wav")
Schema.voices.Add("Overwatch", "Right", "Right.", "npc/metropolice/shooter04.wav")
Schema.voices.Add("Overwatch", "See him", "Yes, I see him.", "npc/metropolice/shooter05.wav")
Schema.voices.Add("Overwatch", "What the", "What the?", "npc/metropolice/surprise1.wav")

-- You may be wondering why I'm using this class rather than the normal Combine one, well I don't want Airwatch to be able to use the standard combine ones (my Airwatch is a class not a faction). You can change it back if you really want but it doesn't affect anything.
Schema.voices.AddClass("Overwatch", function(client)
	return client:Team() == FACTION_OTA or client:Team() == FACTION_MPF
end)

-- Airwatch voice lines.
Schema.voices.Add("Airwatch", "404", "404 zone.", "npc/overwatch/radiovoice/404zone.wav")
Schema.voices.Add("Airwatch", "Accomplices operating", "Protection teams, be advised. Accomplices operating in area.", "npc/overwatch/radiovoice/accomplicesoperating.wav")
Schema.voices.Add("Airwatch", "Administer", "Administer.", "npc/overwatch/radiovoice/administer.wav")
Schema.voices.Add("Airwatch", "No activity", "Airwatch copies no activity in location.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav")
Schema.voices.Add("Airwatch", "Possible miscount", "Airwatch reports possible miscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav")
Schema.voices.Add("Airwatch", "62 alarms", "62 alarms.", "npc/overwatch/radiovoice/alarms62.wav")
Schema.voices.Add("Airwatch", "Code 3", "All teams respond, code 3.", "npc/overwatch/radiovoice/allteamsrespondcode3.wav")
Schema.voices.Add("Airwatch", "Forward pressure", "All units, apply forward pressure.", "npc/overwatch/radiovoice/applyforwardpressure.wav")
Schema.voices.Add("Airwatch", "Units at", "All units at", "npc/overwatch/radiovoice/allunitsat.wav")
Schema.voices.Add("Airwatch", "Witness sterilization", "All units, begin witness sterilization.", "npc/overwatch/radiovoice/allunitsbeginwitnesssterilization.wav")
Schema.voices.Add("Airwatch", "243 suspect", "All units, BOL for 243 suspect.", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav")
Schema.voices.Add("Airwatch", "Terminal verdict", "All units deliver terminal verdict immediately.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav")
Schema.voices.Add("Airwatch", "Code 12", "All units return to code 12.", "npc/overwatch/radiovoice/allunitsreturntocode12.wav")
Schema.voices.Add("Airwatch", "Verdict code", "All units, verdict code is", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav")
Schema.voices.Add("Airwatch", "Verdict code on suspect", "All units, verdict code on suspect", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav")
Schema.voices.Add("Airwatch", "Amputate", "Amputate.", "npc/overwatch/radiovoice/amputate.wav")
Schema.voices.Add("Airwatch", "Anti-citizen", "Anti-citizen.", "npc/overwatch/radiovoice/anticitizen.wav")
Schema.voices.Add("Airwatch", "Anti-fatigue", "Anti-fatigue ration is now 3 milligrams.", "npc/overwatch/radiovoice/antifatigueration3mg.wav")
Schema.voices.Add("Airwatch", "Apply", "Apply.", "npc/overwatch/radiovoice/apply.wav")
Schema.voices.Add("Airwatch", "243", "243 assault on protection team.", "npc/overwatch/radiovoice/assault243.wav")
Schema.voices.Add("Airwatch", "27", "27 attempted crime.", "npc/overwatch/radiovoice/attemptedcrime27.wav")
Schema.voices.Add("Airwatch", "Attention", "Attention.", "npc/overwatch/radiovoice/attention.wav")
Schema.voices.Add("Airwatch", "Charged with", "Attention, you have been charged with", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav")
Schema.voices.Add("Airwatch", "10-0", "10-0, begin scanning.", "npc/overwatch/radiovoice/beginscanning10-0.wav")
Schema.voices.Add("Airwatch", "Block", "Block.", "npc/overwatch/radiovoice/block.wav")
Schema.voices.Add("Airwatch", "Canal block", "Canal block.", "npc/overwatch/radiovoice/canalblock.wav")
Schema.voices.Add("Airwatch", "Capital malcompliance", "Capital malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav")
Schema.voices.Add("Airwatch", "Cauterize", "Cauterize.", "npc/overwatch/radiovoice/cauterize.wav")
Schema.voices.Add("Airwatch", "Citizen", "Citizen.", "npc/overwatch/radiovoice/citizen.wav")
Schema.voices.Add("Airwatch", "Sentencing", "All protection team units: complete sentencing at will.", "npc/overwatch/radiovoice/completesentencingatwill.wav")
Schema.voices.Add("Airwatch", "Condemned zone", "Condemned zone.", "npc/overwatch/radiovoice/condemnedzone.wav")
Schema.voices.Add("Airwatch", "UPI alert", "Team: confirm UPI alert.", "npc/overwatch/radiovoice/confirmupialert.wav")
Schema.voices.Add("Airwatch", "63", "63 criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav")
Schema.voices.Add("Airwatch", "Control section", "Politi control section.", "npc/overwatch/radiovoice/controlsection.wav")
Schema.voices.Add("Airwatch", "Defender", "Defender.", "npc/overwatch/radiovoice/defender.wav")
Schema.voices.Add("Airwatch", "Restricted block", "Restricted block.", "npc/overwatch/radiovoice/deservicesarea.wav")
Schema.voices.Add("Airwatch", "Destruction", "404 zone.", "npc/overwatch/radiovoice/destructionofcpt.wav")
Schema.voices.Add("Airwatch", "Sociocidal", "Divisive sociocidal counter-obeyance.", "npc/overwatch/radiovoice/devisivesociocidal.wav")
Schema.voices.Add("Airwatch", "Disassociation", "Disassociation from the civic populace.", "npc/overwatch/radiovoice/disassociationfromcivic.wav")
Schema.voices.Add("Airwatch", "Disengaged", "647e disengaged from workforce.", "npc/overwatch/radiovoice/dissengaged647e.wav")
Schema.voices.Add("Airwatch", "Distribution block", "Distribution block.", "npc/overwatch/radiovoice/distribution block.wav")
Schema.voices.Add("Airwatch", "10-103m", "10-103m disturbance by mentally unfit.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav")
Schema.voices.Add("Airwatch", "415", "415 civic disunity.", "npc/overwatch/radiovoice/disturbingunity415.wav")
Schema.voices.Add("Airwatch", "Document", "Document.", "npc/overwatch/radiovoice/document.wav")
Schema.voices.Add("Airwatch", "8", "Eight.", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("Airwatch", "Non Cohesive", "Engaging protection team is non-cohesive.", "npc/overwatch/radiovoice/engagingteamisnoncohesive.wav")
Schema.voices.Add("Airwatch", "Examine", "Examine.", "npc/overwatch/radiovoice/examine.wav")
Schema.voices.Add("Airwatch", "External jurisdiction", "External Jurisdiction.", "npc/overwatch/radiovoice/externaljurisdiction.wav")
Schema.voices.Add("Airwatch", "Failure to comply", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav")
Schema.voices.Add("Airwatch", "Failure to treat outbreak", "Stabilization Team: failure to treat identified local outbreak will force team recall and recycle.", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav")
Schema.voices.Add("Airwatch", "Final verdict", "Final verdict administered.", "npc/overwatch/radiovoice/finalverdictadministered.wav")
Schema.voices.Add("Airwatch", "5", "Five.", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("Airwatch", "Sky shield", "Sky shield.", "npc/overwatch/radiovoice/fmil_region_073.wav")
Schema.voices.Add("Airwatch", "4", "Four.", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("Airwatch", "Freeman", "Freeman.", "npc/overwatch/radiovoice/freeman.wav")
Schema.voices.Add("Airwatch", "17f", "17-F fugitive detatchment.", "npc/overwatch/radiovoice/fugitive17f.wav")
Schema.voices.Add("Airwatch", "Rank points", "50 percent rank points.", "npc/overwatch/radiovoice/halfrankpoints.wav")
Schema.voices.Add("Airwatch", "Reproduction credits", "50 percent reproduction credits.", "npc/overwatch/radiovoice/halfreproductioncredits.wav")
Schema.voices.Add("Airwatch", "Hero", "Hero.", "npc/overwatch/radiovoice/hero.wav")
Schema.voices.Add("Airwatch", "High priority region", "High priority region.", "npc/overwatch/radiovoice/highpriorityregion.wav")
Schema.voices.Add("Airwatch", "95", "95 illegal carrying.", "npc/overwatch/radiovoice/illegalcarrying95.wav")
Schema.voices.Add("Airwatch", "63s", "63s illegal in operation.", "npc/overwatch/radiovoice/illegalinoperation63s.wav")
Schema.voices.Add("Airwatch", "Immediate amputation", "Immediate amputation.", "npc/overwatch/radiovoice/immediateamputation.wav")
Schema.voices.Add("Airwatch", "Industrial zone", "Industrial zone.", "npc/overwatch/radiovoice/industrialzone.wav")
Schema.voices.Add("Airwatch", "Infection", "Infection.", "npc/overwatch/radiovoice/infection.wav")
Schema.voices.Add("Airwatch", "Infested zone", "Infested zone.", "npc/overwatch/radiovoice/infestedzone.wav")
Schema.voices.Add("Airwatch", "Inject", "Inject.", "npc/overwatch/radiovoice/inject.wav")
Schema.voices.Add("Airwatch", "Inoculate", "Inoculate.", "npc/overwatch/radiovoice/innoculate.wav")
Schema.voices.Add("Airwatch", "In progress", "In progress.", "npc/overwatch/radiovoice/inprogress.wav")
Schema.voices.Add("Airwatch", "Intercede", "Intercede.", "npc/overwatch/radiovoice/intercede.wav")
Schema.voices.Add("Airwatch", "Interlock", "Interlock.", "npc/overwatch/radiovoice/interlock.wav")
Schema.voices.Add("Airwatch", "Investigate", "Investigate.", "npc/overwatch/radiovoice/investigate.wav")
Schema.voices.Add("Airwatch", "Investigate and report", "Investigate and report.", "npc/overwatch/radiovoice/investigateandreport.wav")
Schema.voices.Add("Airwatch", "is now", "is now", "npc/overwatch/radiovoice/isnow.wav")
Schema.voices.Add("Airwatch", "Islolate", "Isolate.", "npc/overwatch/radiovoice/isolate.wav")
Schema.voices.Add("Airwatch", "Jury", "Jury.", "npc/overwatch/radiovoice/jury.wav")
Schema.voices.Add("Airwatch", "King", "King.", "npc/overwatch/radiovoice/king.wav")
Schema.voices.Add("Airwatch", "Report ratios", "Attention Stabilization Team leaders: Report de-serviced unit to sterilized body count ratio for reinforcement, reward, or removal processing.", "npc/overwatch/radiovoice/leadersreportratios.wav")
Schema.voices.Add("Airwatch", "L5 Activity", "Level-5 anti civil activity.", "npc/overwatch/radiovoice/level5anticivilactivity.wav")
Schema.voices.Add("Airwatch", "Line", "Line.", "npc/overwatch/radiovoice/line.wav")
Schema.voices.Add("Airwatch", "Lock", "Lock.", "npc/overwatch/radiovoice/lock.wav")
Schema.voices.Add("Airwatch", "Lockdown location", "Protection team: Lock down your location, SACRIFICE code..", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav")
Schema.voices.Add("Airwatch", "Lost biosignal", "Lost biosignal for protection team unit", "npc/overwatch/radiovoice/lostbiosignalforunit.wav")
Schema.voices.Add("Airwatch", "9", "Nine.", "npc/overwatch/radiovoice/nine.wav")
Schema.voices.Add("Airwatch", "Non citizen", "Non-citizen.", "npc/overwatch/radiovoice/noncitizen.wav")
Schema.voices.Add("Airwatch", "No patrol region", "No-patrol region.", "npc/overwatch/radiovoice/lock.wav")
Schema.voices.Add("Airwatch", "51", "51 non-sanctioned arson.", "npc/overwatch/radiovoice/nonsanctionedarson51.wav")
Schema.voices.Add("Airwatch", "Officer", "Officer.", "npc/overwatch/radiovoice/officerat.wav")
Schema.voices.Add("Airwatch", "Closing on suspect", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav")
Schema.voices.Add("Airwatch", "1", "One.", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("Airwatch", "Outland zone", "Outland zone.", "npc/overwatch/radiovoice/outlandzone.wav")
Schema.voices.Add("Airwatch", "Patrol", "Patrol.", "npc/overwatch/radiovoice/patrol.wav")
Schema.voices.Add("Airwatch", "Off world assignment", "Permanent off-world service assignment.", "npc/overwatch/radiovoice/permanentoffworld.wav")
Schema.voices.Add("Airwatch", "Politistabilization marginal", "Notice: Protection Teams: civic politistabilization index is marginal.", "npc/overwatch/radiovoice/politistabilizationmarginal.wav")
Schema.voices.Add("Airwatch", "69", "69 possession of resources.", "npc/overwatch/radiovoice/posession69.wav")
Schema.voices.Add("Airwatch", "Premature mission termination", "Premature mission termination will result in", "npc/overwatch/radiovoice/prematuremissiontermination.wav")
Schema.voices.Add("Airwatch", "Prepare final sentencing", "Prepare for final sentencing.", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav")
Schema.voices.Add("Airwatch", "Prepare to inoculate", "Prepare to inoculate.", "npc/overwatch/radiovoice/preparetoinnoculate.wav")
Schema.voices.Add("Airwatch", "Prepare to recieve verdict", "Prepare to recieve verdict.", "npc/overwatch/radiovoice/preparetorecieveverdict.wav")
Schema.voices.Add("Airwatch", "Visual download", "Attention: prepare visual download of anti-citizen one.", "npc/overwatch/radiovoice/preparevisualdownload.wav")
Schema.voices.Add("Airwatch", "Preserve", "Preserve.", "npc/overwatch/radiovoice/preserve.wav")
Schema.voices.Add("Airwatch", "Pressure", "Pressure.", "npc/overwatch/radiovoice/pressure.wav")
Schema.voices.Add("Airwatch", "Production block", "Production block.", "npc/overwatch/radiovoice/productionblock.wav")
Schema.voices.Add("Airwatch", "Promoting unrest", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav")
Schema.voices.Add("Airwatch", "Prosecute", "Prosecute.", "npc/overwatch/radiovoice/prosecute.wav")
Schema.voices.Add("Airwatch", "507", "507 public non-compliance.", "npc/overwatch/radiovoice/publicnoncompliance507.wav")
Schema.voices.Add("Airwatch", "Quick", "Quick.", "npc/overwatch/radiovoice/quick.wav")
Schema.voices.Add("Airwatch", "Recalibrate socioscan", "Team: recalibrate socioscan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav")
Schema.voices.Add("Airwatch", "Conflicting data", "We are recieving conflicting data.", "npc/overwatch/radiovoice/recievingconflictingdata.wav")
Schema.voices.Add("Airwatch", "99", "99 reckless operation.", "npc/overwatch/radiovoice/recklessoperation99.wav")
Schema.voices.Add("Airwatch", "Code 3", "Reinforcement teams: code 3.", "npc/overwatch/radiovoice/reinforcementteamscode3.wav")
Schema.voices.Add("Airwatch", "Remaining units contain", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav")
Schema.voices.Add("Airwatch", "100 credits", "Rank leader: reminder: 100 sterilized credits qualifies non-mechanical reproduction simulation.", "npc/overwatch/radiovoice/reminder100credits.wav")
Schema.voices.Add("Airwatch", "Memory replacement", "Reminder: memory replacement is the first step toward rank privileges.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav")
Schema.voices.Add("Airwatch", "Report on", "Local protection team units report on", "npc/overwatch/radiovoice/reporton.wav")
Schema.voices.Add("Airwatch", "Report please", "Report, please.", "npc/overwatch/radiovoice/reportplease.wav")
Schema.voices.Add("Airwatch", "Repurposed area", "Repurposed area.", "npc/overwatch/radiovoice/repurposedarea.wav")
Schema.voices.Add("Airwatch", "Residential block", "Residential block.", "npc/overwatch/radiovoice/residentialblock.wav")
Schema.voices.Add("Airwatch", "148", "148 resisting arrest.", "npc/overwatch/radiovoice/resistingpacification148.wav")
Schema.voices.Add("Airwatch", "Respond", "Respond.", "npc/overwatch/radiovoice/respond.wav")
Schema.voices.Add("Airwatch", "Restrict", "Restrict.", "npc/overwatch/radiovoice/restrict.wav")
Schema.voices.Add("Airwatch", "Restricted incursion", "Restricted incursion in progress.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav")
Schema.voices.Add("Airwatch", "Family cohesion", "Reward notice: protectiont team member, your family cohesion is preserved.", "npc/overwatch/radiovoice/rewardnotice.wav")
Schema.voices.Add("Airwatch", "404 riot", "404 riot.", "npc/overwatch/radiovoice/riot404.wav")
Schema.voices.Add("Airwatch", "Roller", "Roller.", "npc/overwatch/radiovoice/roller.wav")
Schema.voices.Add("Airwatch", "Search", "Search.", "npc/overwatch/radiovoice/search.wav")
Schema.voices.Add("Airwatch", "Sector", "Sector.", "npc/overwatch/radiovoice/sector.wav")
Schema.voices.Add("Airwatch", "Serve", "Serve.", "npc/overwatch/radiovoice/serve.wav")
Schema.voices.Add("Airwatch", "7", "Seven.", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("Airwatch", "6", "Six.", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("Airwatch", "Social fracture", "Social fracture in progress. Respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav")
Schema.voices.Add("Airwatch", "Sociocide", "Sociocide.", "npc/overwatch/radiovoice/sociocide.wav")
Schema.voices.Add("Airwatch", "Sociostabilization restored", "Sociostabilization restored.", "npc/overwatch/radiovoice/sociostabilizationrestored.wav")
Schema.voices.Add("Airwatch", "Stabilization jurisdiction", "Quick.", "npc/overwatch/radiovoice/stabilizationjurisdiction.wav")
Schema.voices.Add("Airwatch", "Station block", "Station block.", "npc/overwatch/radiovoice/stationblock.wav")
Schema.voices.Add("Airwatch", "Status on 243 suspect", "All units: report status on 243 suspect.", "npc/overwatch/radiovoice/statuson243suspect.wav")
Schema.voices.Add("Airwatch", "Sterilize", "Sterilize.", "npc/overwatch/radiovoice/sterilize.wav")
Schema.voices.Add("Airwatch", "Stick", "Stick.", "npc/overwatch/radiovoice/stick.wav")
Schema.voices.Add("Airwatch", "Storm system", "Storm system.", "npc/overwatch/radiovoice/stormsystem.wav")
Schema.voices.Add("Airwatch", "Subject", "Subject.", "npc/overwatch/radiovoice/subject.wav")
Schema.voices.Add("Airwatch", "Subject is 187", "Subject is now 187.", "npc/overwatch/radiovoice/suspectisnow187.wav")
Schema.voices.Add("Airwatch", "Suspect malignant", "Suspect is judged malignant. Verdict code is", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav")
Schema.voices.Add("Airwatch", "Suspend", "Suspend.", "npc/overwatch/radiovoice/suspend.wav")
Schema.voices.Add("Airwatch", "Suspend negotiations", "Suspend negotiations.", "npc/overwatch/radiovoice/suspendnegotiations.wav")
Schema.voices.Add("Airwatch", "tac 3", "All units: switch comm to tac 3.", "npc/overwatch/radiovoice/switchcomtotac3.wav")
Schema.voices.Add("Airwatch", "tac 5", "All units switch com to tac 5 and report in to command point.", "npc/overwatch/radiovoice/switchtotac5reporttocp.wav")
Schema.voices.Add("Airwatch", "Tap", "Tap.", "npc/overwatch/radiovoice/tap.wav")
Schema.voices.Add("Airwatch", "Report status", "Local civil protection teams report status.", "npc/overwatch/radiovoice/teamsreportstatus.wav")
Schema.voices.Add("Airwatch", "Terminal prosecution", "Terminal prosecution.", "npc/overwatch/radiovoice/terminalprosecution.wav")
Schema.voices.Add("Airwatch", "Terminal restriction zone", "Terminal restriction zone.", "npc/overwatch/radiovoice/terminalrestrictionzone.wav")
Schema.voices.Add("Airwatch", "51b", "51-B threat to property.", "npc/overwatch/radiovoice/threattoproperty51b.wav")
Schema.voices.Add("Airwatch", "3", "Three.", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("Airwatch", "Transit block", "Transit block.", "npc/overwatch/radiovoice/transitblock.wav")
Schema.voices.Add("Airwatch", "2", "Two.", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("Airwatch", "Union", "Union.", "npc/overwatch/radiovoice/union.wav")
Schema.voices.Add("Airwatch", "Unit deservices", "Unit deservices.", "npc/overwatch/radiovoice/unitdeserviced.wav")
Schema.voices.Add("Airwatch", "Unit down at", "Unit down at", "npc/overwatch/radiovoice/unitdownat.wav")
Schema.voices.Add("Airwatch", "603", "603 unlawful entry.", "npc/overwatch/radiovoice/unlawfulentry603.wav")
Schema.voices.Add("Airwatch", "UPI", "UPI.", "npc/overwatch/radiovoice/upi.wav")
Schema.voices.Add("Airwatch", "Vice", "Vice.", "npc/overwatch/radiovoice/vice.wav")
Schema.voices.Add("Airwatch", "Victor", "Victor.", "npc/overwatch/radiovoice/victor.wav")
Schema.voices.Add("Airwatch", "Violation of civic trust", "Violation of civic trust.", "npc/overwatch/radiovoice/violationofcivictrust.wav")
Schema.voices.Add("Airwatch", "Waste river", "Waste river.", "npc/overwatch/radiovoice/wasteriver.wav")
Schema.voices.Add("Airwatch", "94", "94 weapon.", "npc/overwatch/radiovoice/weapon94.wav")
Schema.voices.Add("Airwatch", "Workforce Intake Hub", "Workforce intake hub.", "npc/overwatch/radiovoice/workforceintakehub.wav")
Schema.voices.Add("Airwatch", "Xray", "Xray.", "npc/overwatch/radiovoice/xray.wav")
Schema.voices.Add("Airwatch", "Yellow", "Yellow.", "npc/overwatch/radiovoice/yellow.wav")
Schema.voices.Add("Airwatch", "Terminal violations", "You are charged with terminal violations 148, 243, 245.", "npc/overwatch/radiovoice/youarechargedwithterminal.wav")
Schema.voices.Add("Airwatch", "Judged guilty", "You are judged guilty by civil protection team", "npc/overwatch/radiovoice/youarejudgedguilty.wav")
Schema.voices.Add("Airwatch", "0", "Zero.", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("Airwatch", "Zone", "Zone.", "npc/overwatch/radiovoice/zone.wav")

Schema.voices.AddClass("Airwatch", function(client)
	return client:Team() == CLASS_SCN
end)
