PLUGIN.name = "More Combine voicelines"
PLUGIN.author = "Richard Blonski #5295"
PLUGIN.description = "Adds more comb voicelines including dispatch voicelines"
PLUGIN.schema = "HL2 RP"
PLUGIN.license = [[
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
]]
---------------------------------

Schema.voices.Add("comb", "11-99", "11-99, Officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("comb", "404", "404 Zone", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("comb", "404 ZONE", "4040 Zone", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("comb", "ADMINISTER", "Administer", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("comb", "AFFIRMATIVE", "Affirmative", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("comb", "AFFIRMATIVE2", "Affirmative", "npc/metropolice/vo/affirmative2.wav")
Schema.voices.Add("comb", "YOU CAN GO", "Alright, you can go", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("comb", "ALRIGHT YOU CAN GO", "Alright, you can go", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("comb", "ALL UNITS CLOSE ON SUSPECT", "All units close on suspect", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("comb", "UNITS CLOSE ON SUSPECT", "All units close on suspect", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("comb", "ALL UNITS CODE 2", "All units code two", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("comb", "ALL UNITS MAINTAIN THIS CP", "All units maintain this cp", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("comb", "MAINTAIN THIS CP", "All units maintain this cp", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("comb", "ALL UNITS MOVE IN", "All units move in", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("comb", "UNITS MOVE IN", "All units move in", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("comb", "ALL UNITS REPORT LOCATION SUSPECT", "All units report location suspect", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("comb", "REPORT LOCATION SUSPECT", "All units report location suspect", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("comb", "ALL UNITS AT LOCATION RESPOND CODE 3", "All units at location respond code 3", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("comb", "LOCATION RESPOND CODE 3", "All units at location respond code 3", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("comb", "AMPUTATE", "Amputate", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("comb", "ANTICITIZEN", "Anti-citizen", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("comb", "PICKUP 647", "Any pickup eh- sixty fourty seven reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("comb", "APPLY", "Apply", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("comb", "AT CHECKPOINT", "At checkpoint", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("comb", "BACK ME UP IM OUT", "Back me up I'm out!", "npc/metropolice/vo/backmeupimout.wav")
Schema.voices.Add("comb", "IM OUT", "Back me up I'm out!", "npc/metropolice/vo/backmeupimout.wav")
Schema.voices.Add("comb", "BACKUP", "Backup", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("comb", "BLOCK", "Block", "npc/metropolice/vo/block.wav")
Schema.voices.Add("comb", "BREAK HIS COVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("comb", "BREAK COVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("comb", "BUGS", "Bugs", "npc/metropolice/vo/bugs.wav")
Schema.voices.Add("comb", "CANAL", "Canal", "npc/metropolice/vo/bugsontheloose.wav")
Schema.voices.Add("comb", "CANAL BLOCK", "Canal block", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("comb", "BLIP ON READOUT", "Catch that blip on- the stabilization read out", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("comb", "CAUTERIZE", "Cauterize", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("comb", "CHECK FOR MISCOUNT", "Check for miscount", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("comb", "HAHA", "Haha", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("comb", "CITIZEN", "Citzen", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("comb", "CLEAR AND CODE 100", "Clear and code 100", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("comb", "CODE 100", "Code 100", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("comb", "CODE 7", "Code 7", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("comb", "CONDEMNED ZONE", "Condemned zone", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("comb", "CONTROL SECTION", "Control section", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("comb", "CONVERGING", "Converging", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("comb", "COPY", "Copy", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("comb", "COVER ME IM GOING IN", "Cover me I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("comb", "DB COUNT IS", "DB Count is..", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("comb", "DEFENDER", "Defender", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("comb", "DESERVICED AREA", "Deserviced area", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("comb", "DESTROY THAT COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("comb", "DESTROY COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("comb", "DISTRIBUTION BLOCK", "Distribution block", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("comb", "DOCUMENT", "Document", "npc/metropolice/vo/document.wav")
Schema.voices.Add("comb", "DONT MOVE", "Don't move", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("comb", "8", "Eight", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("comb", "EIGHT", "Eight", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("comb", "18", "Eighteen", "npc/metropolice/vo/eighteen.wav")
Schema.voices.Add("comb", "EIGHTEEN", "Eighteen", "npc/metropolice/vo/eighteen.wav")
Schema.voices.Add("comb", "80" , "Eighty", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("comb", "EIGHTY", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("comb", "11", "Eleven", "npc/metropolice/vo/eleven.wav")
Schema.voices.Add("comb", "ELEVEN", "Eleven", "npc/metropolice/vo/eleven.wav")
Schema.voices.Add("comb", "EXAMINE", "Examine", "npc/metropolice/vo/examine.wav")
Schema.voices.Add("comb", "EXPIRED", "Expired", "npc/metropolice/vo/expired.wav")
Schema.voices.Add("comb", "15", "Fifteen", "npc/metropolice/vo/fifteen.wav")
Schema.voices.Add("comb", "FIFTEEN", "Fifteen", "npc/metropolice/vo/fifteen.wav")
Schema.voices.Add("comb", "50", "Fifty", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("comb", "FIFTY", "Fifty", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("comb", "FINAL VERDICT", "Final verdict administered", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("comb", "FINAL WARNING", "Final warning", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("comb", "FIRE TO EXPOSE TARGET", "Fire to expose target", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("comb", "FIRST WARNING MOVE AWAY", "First warning, move away", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("comb", "5", "Five", "npc/metropolice/vo/five.wav")
Schema.voices.Add("comb", "FIVE", "Five", "npc/metropolice/vo/five.wav")
Schema.voices.Add("comb", "14", "Fourteen", "npc/metropolice/vo/fourteen.wav")
Schema.voices.Add("comb", "FOURTEEN", "Fourteen", "npc/metropolice/vo/fourteen.wav")
Schema.voices.Add("comb", "40", "Fourty", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("comb", "FOURTY", "Fourty", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("comb", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("comb", "GET OUT OF HERE", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("comb", "GOING TO TAKE A LOOK", "Going to take a look", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("comb", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("comb", "HELP", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("comb", "HERO", "Hero", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("comb", "HES RUNNING", "Hes running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("comb", "HE IS RUNNING", "Hes running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("comb", "HES UP THERE", "Hes up there", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("comb", "HE IS UP THERE", "Hes up there", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("comb", "HOLD IT", "Hold it", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("comb", "HOLD IT RIGHT THERE", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("comb", "INDUSTRIAL ZONE", "Industrial zone", "npc/metropolice/vo/industrialzone.wav")
Schema.voices.Add("comb", "INFECTION", "Infection", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("comb", "INFESTED ZONE", "Infested zone", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("comb", "INJECT", "Inject", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("comb", "INNOCULATE", "Innoculate", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("comb", "IN POSITION", "In position", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("comb", "IN POSITION HARD POINT", "In position at hardpoint", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("comb", "INTERCEDE", "Intercede", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("comb", "INTERLOCK", "Interlock", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("comb", "INVESTIGATE", "Investigate", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("comb", "I SAID MOVE ALONG", "I said move along!", "npc/metropolice/vo/isaidmovealong.wav")
Schema.voices.Add("comb", "IS DOWN", "Is down!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("comb", "IS A GO", "Is a go", "npc/metropolice/vo/isgo.wav")
Schema.voices.Add("comb", "IS GO", "Is a go", "npc/metropolice/vo/isgo.wav")
Schema.voices.Add("comb", "IS MOVING IN", "Is moving in", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("comb", "ISOLATE", "Isolate", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("comb", "IS PASSIVE", "Is passive", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("comb", "IS READY TO GO", "Is ready to go", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("comb", "JURY", "Jury", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("comb", "KEEP MOVING", "Keep moving", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("comb", "KING", "King", "npc/metropolice/vo/king.wav")
Schema.voices.Add("comb", "LINE", "Line", "npc/metropolice/vo/line.wav")
Schema.voices.Add("comb", "REPORT STATUS", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("comb", "LOCATION", "Location", "npc/metropolice/vo/location.wav")
Schema.voices.Add("comb", "LOCK", "Lock", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("comb", "LOOKING FOR TROUBLE", "Looking for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("comb", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("comb", "METERS", "Meters", "npc/metropolice/vo/meters.wav")
Schema.voices.Add("comb", "MOVE", "Move", "npc/metropolice/vo/move.wav")
Schema.voices.Add("comb", "MOVE ALONG", "Move along", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("comb", "MOVE ALONG2", "Move along", "npc/metropolice/vo/movealong3.wav")
Schema.voices.Add("comb", "MOVE BACK RIGHT NOW", "Move back right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("comb", "MOVE IT", "Move it", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("comb", "MOVE IT2", "Move it", "npc/metropolice/vo/moveit2.wav")
Schema.voices.Add("comb", "MOVING TO COVER", "Moving to cover", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("comb", "MOVING TO HARD POINT", "Moving to hardpoint", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("comb", "MOVING TO HARDPOINT", "Moving to hardpoint", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("comb", "NECROTICS", "Necrotics", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("comb", "NEED ANY HELP WITH THIS ONE", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("comb", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("comb", "9", "Nine", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("comb", "NINE", "Nine", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("comb", "19", "Nineteen", "npc/metropolice/vo/nineteen.wav")
Schema.voices.Add("comb", "NINETEEN", "Nineteen", "npc/metropolice/vo/nineteen.wav")
Schema.voices.Add("comb", "90", "Ninety", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("comb", "NINETY", "Ninety", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("comb", "NO CONTACT", "No contact", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("comb", "NON CITIZEN", "Noncitizen", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("comb", "NONCITIZEN", "Noncitizen", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("comb", "NON PATROL REGION", "Non patrol region", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("comb", "NOW GET OUT", "Now get out of here", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("comb", "NOW GET OUT OF HERE", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("comb", "1", "One", "npc/metropolice/vo/one.wav")
Schema.voices.Add("comb", "ONE", "One", "npc/metropolice/vo/one.wav")
Schema.voices.Add("comb", "100", "One hundred", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("comb", "ONE HUNDRED", "One hundred", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("comb", "OUT BREAK", "Outbreak", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("comb", "OUTBREAK", "Outbreak", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("comb", "OUTLAND ZONE", "Outland zone", "npc/metropolice/vo/outlandzone.wav")
Schema.voices.Add("comb", "PACIFYING", "Pacifying", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("comb", "PATROL", "Patrol", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("comb", "CAN", "Pick up that can", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("comb", "CAN2", "Pick up the can", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("comb", "CAN3", "Pick- pick up the can", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("comb", "CIVIL JUDGEMENT", "Suspect, prepare to recive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("comb", "PRESERVE", "Preserve", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("comb", "PRESSURE", "Pressure", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("comb", "PRODUCTION BLOCK", "Production block", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("comb", "PROSECUTE", "Prosecute", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("comb", "PROTECTION COMPLETE", "Protection complete", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("comb", "CAN4", "Now put it in the trash can", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("comb", "CAN5", "I've said put it in the trash can", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("comb", "QUICK", "Quick", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("comb", "READY TO AMPUTATE", "Ready to amputate", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("comb", "READY TO JUDGE", "Ready to judge", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("comb", "READY TO PROSECUTE", "Ready to prosecute", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("comb", "CODE 3", "Reinforcements teams code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("comb", "RESPONDING", "Responding", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("comb", "RESTRICT", "Restrict", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("comb", "RODGER THAT", "Rodger that", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("comb", "ROLLER", "Roller", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("comb", "SEARCH", "Search", "npc/metropolice/vo/search.wav")
Schema.voices.Add("comb", "SECTOR", "Sector", "npc/metropolice/vo/sector.wav")
Schema.voices.Add("comb", "SERVE", "Serve", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("comb", "7", "Seven", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("comb", "SEVEN", "Seven", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("comb", "17", "Seventeen", "npc/metropolice/vo/seventeen.wav")
Schema.voices.Add("comb", "SEVENTEEN", "npc/metropolice/vo/seventeen.wav")
Schema.voices.Add("comb", "70", "Seventy", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("comb", "SEVENTY", "Seventy", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("comb", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("comb", "SIX", "Six", "npc/metropolice/vo/six.wav")
Schema.voices.Add("comb", "6", "Six", "npc/metropolice/vo/six.wav")
Schema.voices.Add("comb", "16", "Sixteen", "npc/metropolice/vo/sixteen.wav")
Schema.voices.Add("comb", "SIXTEEN", "Sixteen", "npc/metropolice/vo/sixteen.wav")
Schema.voices.Add("comb", "60", "Sixty", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("comb", "SIXTY", "Sixty", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("comb", "SOCIOCIDE", "Sociocide", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("comb", "STATION BLOCK", "Station block", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("comb", "STERILLZE", "Sterillze", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("comb", "STICK", "Stick", "npc/metropolice/vo/stick.wav")
Schema.voices.Add("comb", "STORMSYSTEM", "Storm system", "npc/metropolice/vo/stormsystem.wav")
Schema.voices.Add("comb", "STORM SYSTEM", "Storm system", "npc/metropolice/vo/stormsystem.wav")
Schema.voices.Add("comb", "SUBJECT", "Subject", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("comb", "SUSPEND", "Suspend", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("comb", "TAKE COVER", "Take cover", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("comb", "TAP", "Tap", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("comb", "10", "Ten", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("comb", "Ten", "Ten", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("comb", "10-2", "10-2", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("comb", "10-4", "10-4", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("comb", "10-8", "10-8, standing by", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("comb", "THERE HE IS", "There he is", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("comb", "13", "Thirteen", "npc/metropolice/vo/thirteen.wav")
Schema.voices.Add("comb", "THIRTEEN", "Thirteen", "npc/metropolice/vo/thirteen.wav")
Schema.voices.Add("comb", "30", "Thirty", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("comb", "THIRTY", "Thirty", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("comb", "SECOND WARNING", "This is your second warning", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("comb", "THREE", "Three", "npc/metropolice/vo/three.wav")
Schema.voices.Add("comb", "3", "Three", "npc/metropolice/vo/three.wav")
Schema.voices.Add("comb", "300", "Three hundred", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("comb", "THREEHUNDRED", "Three hundred", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("comb", "TRANSIT BLOCK", "Transit block", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("comb", "12", "Twelve", "npc/metropolice/vo/twelve.wav")
Schema.voices.Add("comb", "TWELVE", "Twelve", "npc/metropolice/vo/twelve.wav")
Schema.voices.Add("comb", "20", "Twenty", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("comb", "TWENTY", "Twenty", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("comb", "2", "Two", "npc/metropolice/vo/two.wav")
Schema.voices.Add("comb", "TWO", "Two", "npc/metropolice/vo/two.wav")
Schema.voices.Add("comb", "200", "Two hundred", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("comb", "TWO HUNDRED", "Two hundred", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("comb", "UNION", "Union", "npc/metropolice/vo/union.wav")
Schema.voices.Add("comb", "UPI", "UPI", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("comb", "UTL SUSPECT", "UTL Suspect", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("comb", "VACATE", "Vacate citizen", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("comb", "VACATE CITIZEN", "Vacate citizen", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("comb", "VICE", "Vice", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("comb", "VICTOR", "Victor", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("comb", "WATCH IT", "Watch it", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("comb", "WORK FORCE IN TAKE", "Workforce intake", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("comb", "WORKFORCE INTAKE", "Workforce intake", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("comb", "XRAY", "Xray", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("comb", "YELLOW", "Yellow", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("comb", "ZERO", "Zero", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("comb", "0", "Zero", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("comb", "ZONE", "Zone", "npc/metropolice/vo/zone.wav")
Schema.voices.Add("comb", "DROP YOUR WEAPON", "Drop your weapon get down!", "npc/metropolice/dropweapon.wav")
Schema.voices.Add("comb", "DROP YOUR WEAPON GET DOWN", "Drop your weapon get down!", "npc/metropolice/dropweapon.wav")
Schema.voices.Add("comb", "FREEZE", "Freeze!", "npc/metropolice/freeze.wav")
Schema.voices.Add("comb", "GET ON THE GROUND", "Stay where you are, get on the ground, do it now!", "npc/metropolice/getonground.wav")
Schema.voices.Add("comb", "GET OUT OF THERE", "Get out of there!", "npc/metropolice/hiding01.wav")
Schema.voices.Add("comb", "THERE IS NO POINT IN HIDING", "There is no point in hiding", "npc/metropolice/hiding02.wav")
Schema.voices.Add("comb", "YOU HAVE NO CHANCE OF ESCAPE", "You have no chance of escape", "npc/metropolice/hiding03.wav")
Schema.voices.Add("comb", "YOUR SURROUNDED", "Your surrounded!", "npc/metropolice/hiding04.wav")
Schema.voices.Add("comb", "WE HAVE YOU COVERED", "We have you covered", "npc/metropolice/hiding05.wav")
Schema.voices.Add("comb", "HIDING", "Get out of there!", "npc/metropolice/hiding01.wav")
Schema.voices.Add("comb", "HIDING2", "Theres no point in hiding", "npc/metropolice/hiding02.wav")
Schema.voices.Add("comb", "HIDING3", "You have no chance of escape", "npc/metropolice/hiding03.wav")
Schema.voices.Add("comb", "HIDING4", "Your surrounded!", "npc/metropolice/hiding04.wav")
Schema.voices.Add("comb", "HIDING5", "We have you covered", "npc/metropolice/hiding05.wav")
Schema.voices.Add("comb", "FIGURES", "Figures", "npc/metropolice/mc1ans_figures.wav")
Schema.voices.Add("comb", "HM", "Hmm", "npc/metropolice/mc1ans_figures.wav")
Schema.voices.Add("comb", "HUH FIGURES", "npc/metropolice/mc1ans_huhfigures.wav")
Schema.voices.Add("comb", "FIGURES2", "npc/metropolice/mc1ans_huhfigures.wav")
Schema.voices.Add("comb", "LET ME THINK ABOUT THAT", "Ah- Let me think about that", "npc/metropolice/mc1ans_letmethink.wav")
Schema.voices.Add("comb", "MIGHT BE", "Might be", "npc/metropolice/mc1ans_mightbe.wav")
Schema.voices.Add("comb", "MIGHT COULD", "Might could", "npc/metropolice/mc1ans_mightcould.wav")
Schema.voices.Add("comb", "MIGHT NOT", "Might not", "npc/metropolice/mc1ans_mightnot.wav")
Schema.voices.Add("comb", "NOPE", "Nope", "npc/metropolice/mc1ans_nope.wav")
Schema.voices.Add("comb", "I RATHER NOT TALK ABOUT THAT", "I Rather not talk about that", "npc/metropolice/mc1ans_rathernottalk.wav")
Schema.voices.Add("comb", "I RATHER NOT THINK ABOUT THAT", "I Rather not think about that", "npc/metropolice/mc1ans_rathernotthink.wav")
Schema.voices.Add("comb", "I WOULD SHUT UP ABOUT THAT", "I would shutup about that", "npc/metropolice/mc1ans_shutup.wav")
Schema.voices.Add("comb", "I WOULD SHUTUP ABOUT THAT", "I would shutup about that", "npc/metropolice/mc1ans_shutup.wav")
Schema.voices.Add("comb", "STOP WHINING", "Stop whining", "npc/metropolice/mc1ans_stopwhining.wav")
Schema.voices.Add("comb", "THERE IS YOUR PROBLEM RIGHT THERE", "There is your problem right there", "npc/metropolice/mc1ans_theresyerproblem.wav")
Schema.voices.Add("comb", "THERE IS YOUR PROBLEM", "There is your problem right there", "npc/metropolice/mc1ans_theresyerproblem.wav")
Schema.voices.Add("comb", "THINK SO", "Think so", "npc/metropolice/mc1ans_thinkso.wav")
Schema.voices.Add("comb", "WATCH YOUR MOUTH", "Watch your mouth", "npc/metropolice/mc1ans_watchyermouth.wav")
Schema.voices.Add("comb", "YEAH", "Yeah", "npc/metropolice/mc1ans_yeah.wav")
Schema.voices.Add("comb", "YUP", "Yup", "npc/metropolice/mc1ans_yep.wav")
Schema.voices.Add("comb", "YOU EXPECT ME", "You expect me to belive that?", "npc/metropolice/mc1ans_youexpectme.wav")
Schema.voices.Add("comb", "YOU EXPECT ME TO BELIVE THAT", "You expect me to belive that?", "npc/metropolice/mc1ans_youexpectme.wav")
Schema.voices.Add("comb", "YOU REALLY BELIVE THAT", "You really belive that?", "npc/metropolice/mc1ans_youreallybelieve.wav")
Schema.voices.Add("comb", "I GOT BETTER THINGS TO DO", "I got better things to do", "npc/metropolice/mc1que_betterthings.wav")
Schema.voices.Add("comb", "CARRER", "Yup this was defintely the best carrer choice", "npc/metropolice/mc1que_career.wav")
Schema.voices.Add("comb", "YUP THIS WAS DEFINTELY THE BEST CARRER CHOICE", "Yup this was defintely the best carrer choice", "npc/metropolice/mc1que_career.wav")
Schema.voices.Add("comb", "THIS IS EVERYTHING IVE HOPED IT WOULD BE", "This is everything I've hoped it would be", "'npc/metropolice/mc1que_everythingihoped.wav")
Schema.voices.Add("comb", "IM FEELING PRETTY GOOD", "I'm Feeling pretty good about my self today", "npc/metropolice/mc1que_feelinggood.wav")
Schema.voices.Add("comb", "MY FEET ARE KILLING ME", "My feet are killing me", "npc/metropolice/mc1que_feetkillin.wav")
Schema.voices.Add("comb", "I JUST THOUGHT OF SOMETHING", "I just thought of something.. huh, wait.. maybe not", "npc/metropolice/mc1que_justthought.wav")
Schema.voices.Add("comb", "PEOPLE SUCK", "People suck, well expect from us I mean", "npc/metropolice/mc1que_peoplesuck.wav")
Schema.voices.Add("comb", "LOOK", "Look", "npc/metropolice/pointer03.wav")
Schema.voices.Add("comb", "GOT HIM", "Got him!", "npc/metropolice/shooter01.wav")
Schema.voices.Add("comb", "I HAVE IT", "I have it", "npc/metropolice/shooter02.wav")
Schema.voices.Add("comb", "HE IS MINE", "He is mine", "npc/metropolice/shooter03.wav")
Schema.voices.Add("comb", "RIGHT", "Right", "npc/metropolice/shooter04.wav")
Schema.voices.Add("comb", "YES I SEE HIM", "Yes I see him", "npc/metropolice/shooter05.wav")
Schema.voices.Add("comb", "WHAT THE", "What the-", "npc/metropolice/surprise1.wav")
Schema.voices.Add("comb", "SUPRISED", "What the-", "npc/metropolice/surprise1.wav")
Schema.voices.Add("comb", "HUH", "Huh?!", "npc/metropolice/surprise2.wav")
Schema.voices.Add("comb", "SUPRISED2", "Huh?!", "npc/metropolice/surprise2.wav")
Schema.voices.Add("comb", "SUPRISED3", "What the hell?!", "npc/metropolice/surprise4.wav")
Schema.voices.Add("comb", "WHAT THE HELL", "What the hell?!", "npc/metropolice/surprise4.wav")
Schema.voices.Add("comb", "TAKE HIM DOWN", "Take him down!", "npc/metropolice/takedown.wav")


-- Dispatch local
Schema.voices.Add("comb", "DS 404 ZONE", "404 Zone", "npc/overwatch/radiovoice/404zone.wav")
Schema.voices.Add("comb", "DS ACCOMPLICES OPRERATING IN AREA", "Protection team be adviced, accomplices opreating in area", "npc/overwatch/radiovoice/accomplicesoperating.wav")
Schema.voices.Add("comb", "DS ADMINISTER", "Administer", "npc/overwatch/radiovoice/administer.wav")
Schema.voices.Add("comb", "DS AIRWATCH COPIES NO ACTIVITY IN LOCATION", "Airwatch copies no activity in location", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav")
Schema.voices.Add("comb", "DS AIRWATCH REPORTS POSSIBLE MISCOUNT", "Airwatch reports possible miscount", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav")
Schema.voices.Add("comb", "DS CODE 3", "All teams response code 3", "npc/overwatch/radiovoice/allteamsrespondcode3.wav")
Schema.voices.Add("comb", "DS ALL TEAMS RESPONSE CODE 3", "npc/overwatch/radiovoice/allteamsrespondcode3.wav")
Schema.voices.Add("comb", "DS APPLY FORWARD PRESSURE", "All units apply forwad pressure", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav")
Schema.voices.Add("comb", "DS WITHNESS STERILLZATION", "All units begin withness sterillzation", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav")
Schema.voices.Add("comb", "DS DELIVER TERMINAL VERDICT", "All units deliver terminal verdict immediately", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav")
Schema.voices.Add("comb", "DS ALL UNITS RETURN TO CODE 12", "All units return to code 12", "npc/overwatch/radiovoice/allunitsreturntocode12.wav")
Schema.voices.Add("comb", "DS CODE 12", "All units return to code 12", "npc/overwatch/radiovoice/allunitsreturntocode12.wav")
Schema.voices.Add("comb", "DS ALL UNITS VERDICT CODE ON SUSPECT", "All units verdict code on suspect", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav")
Schema.voices.Add("comb", "DS AMPUTATE", "Amputate", "npc/overwatch/radiovoice/amputate.wav")
Schema.voices.Add("comb", "DS APPLY", "Apply", "npc/overwatch/radiovoice/apply.wav")
Schema.voices.Add("comb", "DS 243", "243, Assault on protection team", "npc/overwatch/radiovoice/assault243.wav")
Schema.voices.Add("comb", "DS 27", "27, Attempted crime", "npc/overwatch/radiovoice/attemptedcrime27.wav")
Schema.voices.Add("comb", "DS ATTENTION", "Attention", "npc/overwatch/radiovoice/attention.wav")
Schema.voices.Add("comb", "DS ATTENTION YOU HAVE BEEN CHARGED WIHT", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav")
Schema.voices.Add("comb", "DS CHARGED WITH", "Attention you have been charged with", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav")
Schema.voices.Add("comb", "DS BEGIN SCANNING", "10-0 Begin scanning", "npc/overwatch/radiovoice/beginscanning10-0.wav")
Schema.voices.Add("comb", "DS BLOCK", "Block", "npc/overwatch/radiovoice/block.wav")
Schema.voices.Add("comb", "DS CANNELBLOCK", "Cannelblock", "npc/overwatch/radiovoice/canalblock.wav")
Schema.voices.Add("comb", "DS CANNEL BLOCK", "Cannelblock", "npc/overwatch/radiovoice/canalblock.wav")
Schema.voices.Add("comb", "DS CAPITAL MALCOMPLINCE", "Capital malcomplice", "npc/overwatch/radiovoice/capitalmalcompliance.wav")
Schema.voices.Add("comb", "DS CAUTERIZE", "Cauterize", "npc/overwatch/radiovoice/cauterize.wav")
Schema.voices.Add("comb", "DS CITIZEN", "Citizen", "npc/overwatch/radiovoice/citizen.wav")
Schema.voices.Add("comb", "DS COMPLETE SENTENCING AT WILL", "All protection teams, complete sentencing at will", "npc/overwatch/radiovoice/completesentencingatwill.wav")
Schema.voices.Add("comb", "DS CODEMENED ZONE", "Codemened zone", "npc/overwatch/radiovoice/condemnedzone.wav")
Schema.voices.Add("comb", "DS CONFIM UPI ALERT", "Team confim UPI alert", "npc/overwatch/radiovoice/confirmupialert.wav")
Schema.voices.Add("comb", "DS 63", "63, crminal trespass", "npc/overwatch/radiovoice/criminaltrespass63.wav")
Schema.voices.Add("comb", "DS DEFENDER", "Defender", "npc/overwatch/radiovoice/defender.wav")
Schema.voices.Add("comb", "DS DESTRUCATION", "Destruction of corporal social protection units", "npc/overwatch/radiovoice/destrutionofcpt.wav")
Schema.voices.Add("comb", "DS DISASSOCIATION FROM THE CIVIC POPULACE", "Disassocaton from the civic poulace", "npc/overwatch/radiovoice/disassociationfromcivic.wav")
Schema.voices.Add("comb", "DS DISTIBUTION BLOCK", "Distribution block", "npc/overwatch/radiovoice/distributionblock.wav")
Schema.voices.Add("comb", "DS 10-103M", "10-103M Disturbance by mentally unfit", "npc/overwatch/radiovoice/disturbancemental10-103m.wav")
Schema.voices.Add("comb", "DS 415", "415, Civic Disunity", "npc/overwatch/radiovoice/disturbingunity415.wav")
Schema.voices.Add("comb", "DS DOCUMENT", "Document", "npc/overwatch/radiovoice/document.wav")
Schema.voices.Add("comb", "DS 8", "Eight", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("comb", "DS EIGHT", "Eight", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("comb", "DS EXAMINE", "Examine", "npc/overwatch/radiovoice/examine.wav")
Schema.voices.Add("comb", "DS EXTERNAL JURISDICTION", "External jurisdiction", "npc/overwatch/radiovoice/externaljurisdiction.wav")
Schema.voices.Add("comb", "DS FAILURE TO COMPLY", "Failure to comply with the civil will", "npc/overwatch/radiovoice/failuretocomply.wav")
Schema.voices.Add("comb", "DS FAILURE TO TREAT OUTBREAK", "Stabilzation team, failure to treat identified local outbreak, will foreseen recall and recycle", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav")
Schema.voices.Add("comb", "DS FINAL VERDICT ADMINISTERED", "Final verdict administered", "npc/overwatch/radiovoice/finalverdictadministered.wav")
Schema.voices.Add("comb", "DS FIVE", "Five", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("comb", "DS 5", "Five", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("comb", "DS START SHIELD", "Start shield", "npc/overwatch/radiovoice/fmil_region 073.wav")
Schema.voices.Add("comb", "DS FOUR", "Four", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("comb", "DS 4", "Four", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("comb", "DS HERO", "Hero", "npc/overwatch/radiovoice/hero.wav")
Schema.voices.Add("comb", "DS HIGH PRIORITY REGION", "High priority region", "npc/overwatch/radiovoice/highpriorityregion.wav")
Schema.voices.Add("comb", "DS 95", "95, illegal carrying", "npc/overwatch/radiovoice/illegalcarrying95.wav")
Schema.voices.Add("comb", "DS 63S", "63s, illegal in operation", "npc/overwatch/radiovoice/illegalinoperation63s.wav")
Schema.voices.Add("comb", "DS IMMEDIATE AMPUTATION", "Immediate amputation", "npc/overwatch/radiovoice/immediateamputation.wav")
Schema.voices.Add("comb", "DS INDUSTRIAL ZONE", "Industrial zone", "npc/overwatch/radiovoice/industrialzone.wav")
Schema.voices.Add("comb", "DS INFECTION", "Infection", "npc/overwatch/radiovoice/infection.wav")
Schema.voices.Add("comb", "DS INFESTED ZONE", "Infested zone", "npc/overwatch/radiovoice/infestedzone.wav")
Schema.voices.Add("comb", "DS INJECT", "Inject", "npc/overwatch/radiovoice/inject.wav")
Schema.voices.Add("comb", "DS INNOCULATE", "Innoculate", "npc/overwatch/radiovoice/innoculate.wav")
Schema.voices.Add("comb", "DS IN PROGRESS", "In progress", "npc/overwatch/radiovoice/inprogress.wav")
Schema.voices.Add("comb", "DS INTERCEDE", "Intercede", "npc/overwatch/radiovoice/intercede.wav")
Schema.voices.Add("comb", "DS INTERLOCK", "Interlock", "npc/overwatch/radiovoice/interlock.wav")
Schema.voices.Add("comb", "DS INVESTIGATE", "Investigate", "npc/overwatch/radiovoice/investigate.wav")
Schema.voices.Add("comb", "DS INVESTIGATE AND REPORT", "Investigate and report", "npc/overwatch/radiovoice/investigateandreport.wav")
Schema.voices.Add("comb", "DS ISOLATE", "Isolate", "npc/overwatch/radiovoice/isolate.wav")
Schema.voices.Add("comb", "DS JURY", "Jury", "npc/overwatch/radiovoice/jury.wav")
Schema.voices.Add("comb", "DS KING", "King", "npc/overwatch/radiovoice/king.wav")
Schema.voices.Add("comb", "DS LEVEL 5 ANTICIVIL ACTIVITY", "Level five anticivil activity", "npc/overwatch/radiovoice/level5anticivilactivity.wav")
Schema.voices.Add("comb", "DS LEVEL 5 ANTI CIVIL ACTIVITY", "npc/overwatch/radiovoice/level5anticivilactivity.wav")
Schema.voices.Add("comb", "DS LINE", "Line", "npc/overwatch/radiovoice/line.wav")
Schema.voices.Add("comb", "DS LOCK", "Lock", "npc/overwatch/radiovoice/lock.wav")
Schema.voices.Add("comb", "DS LOSS BIO SIGNAL", "Loss bio-signal from protection team unit", "npc/overwatch/radiovoice/lostbiosignalforunit.wav")
Schema.voices.Add("comb", "DS 9", "Nine", "npc/overwatch/radiovoice/nine.wav")
Schema.voices.Add("comb", "DS NINE", "Nine", "npc/overwatch/radiovoice/nine.wav")
Schema.voices.Add("comb", "DS NONCITIZEN", "Noncitizen", "npc/overwatch/radiovoice/noncitizen.wav")
Schema.voices.Add("comb", "DS NON CITIZEN", "Noncitizen", "npc/overwatch/radiovoice/noncitizen.wav")
Schema.voices.Add("comb", "DS NO PATROL REGION", "No patrol region", "npc/overwatch/radiovoice/nonpatrolregion.wav")
Schema.voices.Add("comb", "DS 51", "51, non sancationed arson", "npc/overwatch/radiovoice/nonsanctionedarson51.wav")
Schema.voices.Add("comb", "DS OFFICER", "Officer", "npc/overwatch/radiovoice/officerat.wav")
Schema.voices.Add("comb", "DS OFFICER CLOSING ON SUSPECT", "Officer closing on suspect", "npc/overwatch/radiovoice/officerclosingonsuspect.wav")
Schema.voices.Add("comb", "DS OUTLAND ZONE", "Outland zone", "npc/overwatch/radiovoice/outlandzone.wav")
Schema.voices.Add("comb", "DS ONE", "One", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("comb", "DS 1", "One", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("comb", "DS PATROL", "npc/overwatch/radiovoice/patrol.wav")
Schema.voices.Add("comb", "DS PREMANENT OFF WORLD ASSIGNMENT", "Premanent off world assignment", "npc/overwatch/radiovoice/permanentoffworld.wav")
Schema.voices.Add("comb", "DS 69", "69, Passion of resources", "npc/overwatch/radiovoice/posession69.wav")
Schema.voices.Add("comb", "DS PREMATURE MISSION TERMINATION WILL RESULT IN", "Premature mission termination will result in", "npc/overwatch/radiovoice/prematuremissiontermination.wav")
Schema.voices.Add("comb", "DS PREPARE FOR FINAL SENTENCING", "Prepare for final sentencing", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav")
Schema.voices.Add("comb", "DS PREPARE TO INNOCULATE", "All local protection teams units, prepare to innoculate", "npc/overwatch/radiovoice/preparetoinnoculate.wav")
Schema.voices.Add("comb", "DS PREPARE TO RECIVE VERDICT", "Prepare to recive verdict", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav")
Schema.voices.Add("comb", "DS VISUAL DOWNLOAD OF ANTICITIZEN ONE", "Attention, Prepare for visual download of anti-citizen one", "npc/overwatch/radiovoice/preparevisualdownload.wav")
Schema.voices.Add("comb", "DS PRESERVE", "Preserve", "npc/overwatch/radiovoice/preserve.wav")
Schema.voices.Add("comb", "DS PRESSURE", "Pressure", "npc/overwatch/radiovoice/pressure.wav")
Schema.voices.Add("comb", "DS PRODUCTION BLOCK", "Production block", "npc/overwatch/radiovoice/productionblock.wav")
Schema.voices.Add("comb", "DS PROSECUTE", "Prosecute", "npc/overwatch/radiovoice/prosecute.wav")
Schema.voices.Add("comb", "DS PROMOTING COMMUNAL UNREST", "Promoting communal unrest", "npc/overwatch/radiovoice/promotingcommunalunrest.wav")
Schema.voices.Add("comb", "DS PROSCUTE", "Proscute", "npc/overwatch/radiovoice/prosecute.wav")
Schema.voices.Add("comb", "DS 507", "507, Public non-compliance", "npc/overwatch/radiovoice/publicnoncompliance507.wav")
Schema.voices.Add("comb", "DS QUICK", "Quick", "npc/overwatch/radiovoice/quick.wav")
Schema.voices.Add("comb", "DS RECALIBRATE SOCIO SCAN", "Team recalibrate socio scan", "npc/overwatch/radiovoice/recalibratesocioscan.wav")
Schema.voices.Add("comb", "DS WE ARE RECIVING CONFLICTING DATA", "We are reciving conflicting data", "npc/overwatch/radiovoice/recievingconflictingdata.wav")
Schema.voices.Add("comb", "DS 99", "99, Reckless operation", "npc/overwatch/radiovoice/recklessoperation99.wav")
Schema.voices.Add("comb", "DS REMAINING UNITS CONTAIN", "Remaining units contain", "npc/overwatch/radiovoice/remainingunitscontain.wav")
Schema.voices.Add("comb", "DS REMAINDER MEMORY REPLACEMENT", "Remainder, memory replacement is the first step towards rank privliges", "npc/overwatch/radiovoice/remindermemoryreplacement.wav")
Schema.voices.Add("comb", "DS REPORT ON", "Local protection team units report on", "npc/overwatch/radiovoice/reporton.wav")
Schema.voices.Add("comb", "DS REPORT PLEASE", "Report, Please", "npc/overwatch/radiovoice/reportplease.wav")
Schema.voices.Add("comb", "DS REPURPOSED AREA", "Repurposed area", "npc/overwatch/radiovoice/repurposedarea.wav")
Schema.voices.Add("comb", "DS RESIDENTIAL BLOCK", "Residential block", "npc/overwatch/radiovoice/residentialblock.wav")
Schema.voices.Add("comb", "DS 148", "148, Resisting arrest", "npc/overwatch/radiovoice/resistingpacification148.wav")
Schema.voices.Add("comb", "DS RESPOND", "Respond", "npc/overwatch/radiovoice/respond.wav")
Schema.voices.Add("comb", "DS RESTRICT", "Restrict", "npc/overwatch/radiovoice/restrict.wav")
Schema.voices.Add("comb", "DS RESTRICED BLOCK", "Restriced block", "npc/overwatch/radiovoice/restrictedblock.wav")
Schema.voices.Add("comb", "DS RESTRICED INCURSION IN PROGRESS", "Restriced incursion in progress", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav")
Schema.voices.Add("comb", "DS REWARD NOTICE", "Reward notice, Protection team member your family cohesion is preserved", "npc/overwatch/radiovoice/rewardnotice.wav")
Schema.voices.Add("comb", "DS 404", "404 riot", "npc/overwatch/radiovoice/riot404.wav")
Schema.voices.Add("comb", "DS ROLLER", "Roller", "npc/overwatch/radiovoice/roller.wav")
Schema.voices.Add("comb", "DS SEARCH", "Search", "npc/overwatch/radiovoice/search.wav")
Schema.voices.Add("comb", "DS SECTOR", "Sector", "npc/overwatch/radiovoice/sector.wav")
Schema.voices.Add("comb", "DS SERVE", "Serve", "npc/overwatch/radiovoice/serve.wav")
Schema.voices.Add("comb", "DS 7", "Seven", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("comb", "DS SEVEN", "Seven", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("comb", "DS 6", "Six", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("comb", "DS Six", "Six", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("comb", "DS SOCIAL FRACURE IN PROGRESS", "Social fracure in progres, responde", "npc/overwatch/radiovoice/socialfractureinprogress.wav")
Schema.voices.Add("comb", "DS SOCIOCIDE", "Sociocide", "npc/overwatch/radiovoice/sociocide.wav")
Schema.voices.Add("comb", "DS SOCIO STABILZATION RESTORED", "Socio stabilization restored", "npc/overwatch/radiovoice/sociostabilizationrestored.wav")
Schema.voices.Add("comb", "DS STATION BLOCK", "Station block", "npc/overwatch/radiovoice/stationblock.wav")
Schema.voices.Add("comb", "DS STERILZER", "Sterilze", "npc/overwatch/radiovoice/sterilize.wav")
Schema.voices.Add("comb", "DS STICK", "Stick", "npc/overwatch/radiovoice/stick.wav")
Schema.voices.Add("comb", "DS STORM SYSTEM", "Storm system", "npc/overwatch/radiovoice/stormsystem.wav")
Schema.voices.Add("comb", "DS SUBJECT", "Subject", "npc/overwatch/radiovoice/subject.wav")
Schema.voices.Add("comb", "DS SUSPEND", "Suspend", "npc/overwatch/radiovoice/suspend.wav")
Schema.voices.Add("comb", "DS SUSPEND NEGOTIATIONS", "Suspend negotiations", "npc/overwatch/radiovoice/suspendnegotiations.wav")
Schema.voices.Add("comb", "DS SWITCH COM TO TAC 3", "All units, switch com to tac 3", "npc/overwatch/radiovoice/switchcomtotac3.wav")
Schema.voices.Add("comb", "DS SWITCH TO COM TO TAC 5 AND REPORT INTO COMMAND POINT", "All units swtich com to TAC 5 and report to command point", "npc/overwatch/radiovoice/switchtotac5reporttocp.wav")
Schema.voices.Add("comb", "DS TAP", "Tap", "npc/overwatch/radiovoice/tap.wav")
Schema.voices.Add("comb", "DS TERMINAL PROSCUTION", "Terminal proscution", "npc/overwatch/radiovoice/terminalprosecution.wav")
Schema.voices.Add("comb", "DS TERMINAL RESTRICTION ZONE", "Terminal restriction zone", "npc/overwatch/radiovoice/terminalrestrictionzone.wav")
Schema.voices.Add("comb", "DS 51B", "51B, Threat to property", "npc/overwatch/radiovoice/threattoproperty51b.wav")
Schema.voices.Add("comb", "DS 3", "Three", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("comb", "DS THREE", "Three", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("comb", "DS TRANSIT BLOCK", "Transit block", "npc/overwatch/radiovoice/transitblock.wav")
Schema.voices.Add("comb", "DS TWO", "Two", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("comb", "DS 2", "Two", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("comb", "DS UNION", "Union", "npc/overwatch/radiovoice/union.wav")
Schema.voices.Add("comb", "DS UNIT DESERVICED", "Unit deserviced", "npc/overwatch/radiovoice/unitdeserviced.wav")
Schema.voices.Add("comb", "DS UNIT DOWN AT", "Unit down at", "npc/overwatch/radiovoice/unitdownat.wav")
Schema.voices.Add("comb", "DS 603", "603, Unlawful entry", "npc/overwatch/radiovoice/unlawfulentry603.wav")
Schema.voices.Add("comb", "DS UPI", "UPI", "npc/overwatch/radiovoice/upi.wav")
Schema.voices.Add("comb", "DS VICE", "Vice", "npc/overwatch/radiovoice/vice.wav")
Schema.voices.Add("comb", "DS VICTOR", "Victor", "npc/overwatch/radiovoice/victor.wav")
Schema.voices.Add("comb", "DS VIOLATION OF CIVIC TRUST", "Violation of civic trust", "npc/overwatch/radiovoice/violationofcivictrust.wav")
Schema.voices.Add("comb", "DS WAST RIVER", "Wast river", "npc/overwatch/radiovoice/wasteriver.wav")
Schema.voices.Add("comb", "DS 94", "94, Weapon", "npc/overwatch/radiovoice/weapon94.wav")
Schema.voices.Add("comb", "DS WFIH", "Work force in take hub", "npc/overwatch/radiovoice/workforceintake.wav")
Schema.voices.Add("comb", "DS XWAY", "Xway", "npc/overwatch/radiovoice/xray.wav")
Schema.voices.Add("comb", "DS YELLOW", "Yellow", "npc/overwatch/radiovoice/yellow.wav")
Schema.voices.Add("comb", "DS JUDGED GUILTY", "You are judged guilty by civil protection team", "npc/overwatch/radiovoice/youarejudgedguilty.wav")
Schema.voices.Add("comb", "DS ZERO", "Zero", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("comb", "DS 0", "Zero", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("comb", "DS ZONE", "Zone", "npc/overwatch/radiovoice/zone.wav")


-- OVERWATCH
Schema.voices.Add("comb", "ADMINSTER2", "Adminster", "npc/comb_soldier/vo/administer.wav")
Schema.voices.Add("comb", "AFFIRMATIVE3", "Affirmative", "npc/comb_soldier/vo/affirmative.wav")
Schema.voices.Add("comb", "ALERT ONE", "Alert one", "npc/comb_soldier/vo/alert1.wav")
Schema.voices.Add("comb", "ANTI CITIZEN ONE", "Anti-citizen one", "npc/comb_soldier/vo/anticitizenone.wav")
Schema.voices.Add("comb", "ANTISEPTIC", "Antiseptic", "npc/comb_soldier/vo/antiseptic.wav")
Schema.voices.Add("comb", "APEX", "Apex", "npc/comb_soldier/vo/apex.wav")
Schema.voices.Add("comb", "BEARING", "Bearing", "npc/comb_soldier/vo/bearing.wav")
Schema.voices.Add("comb", "BLADE", "Blade", "npc/comb_soldier/vo/blade.wav")
Schema.voices.Add("comb", "BODY PACK HOLDIN", "Body pack holding", "npc/comb_soldier/vo/bodypackholding.wav")
Schema.voices.Add("comb", "BOOMER", "Boomer", "npc/comb_soldier/vo/boomer.wav")
Schema.voices.Add("comb", "BOUNCER", "Bouncer!, Bouncer!", "npc/comb_soldier/vo/bouncerbouncer.wav")
Schema.voices.Add("comb", "CALL HARD POINT", "Call hard point", "npc/comb_soldier/vo/callhotpoint.wav")
Schema.voices.Add("comb", "CLEANED", "Cleaned", "npc/comb_soldier/vo/cleaned.wav")
Schema.voices.Add("comb", "CLOSING", "Closing", "npc/comb_soldier/vo/closing.wav")
Schema.voices.Add("comb", "CONTACT", "Contact", "npc/comb_soldier/vo/contact.wav")
Schema.voices.Add("comb", "CONTACT CONFIM", "Contant confim", "npc/comb_soldier/vo/contactconfim.wav")
Schema.voices.Add("comb", "CONTANT CONFIMED PROSCUTING", "Contant confimed proscuting", "npc/comb_soldier/vo/contactconfirmprosecuting.wav")
Schema.voices.Add("comb", "CONTAINED", "Contained", "npc/comb_soldier/vo/contained.wav")
Schema.voices.Add("comb", "CONTAINMENT PROCEEDING", "Containment proceeding", "npc/comb_soldier/vo/containmentproceeding.wav")
Schema.voices.Add("comb", "COPY2", "Copy", "npc/comb_soldier/vo/copy.wav")
Schema.voices.Add("comb", "COPY THAT", "Copy that", "npc/comb_soldier/vo/copythat.wav")
Schema.voices.Add("comb", "COVER", "Cover", "npc/comb_soldier/vo/cover.wav")
Schema.voices.Add("comb", "COVER ME", "Cover me", "npc/comb_soldier/vo/coverme.wav")
Schema.voices.Add("comb", "DAGGER", "Dagger", "npc/comb_soldier/vo/dagger.wav")
Schema.voices.Add("comb", "DASH", "Dash", "npc/comb_soldier/vo/dash.wav")
Schema.voices.Add("comb", "DEGREES", "Degrees", "npc/comb_soldier/vo/degrees.wav")
Schema.voices.Add("comb", "DELIVERED", "Delivered", "npc/comb_soldier/vo/delivered.wav")
Schema.voices.Add("comb", "DESIGNATE TARGET AS", "Designate target as", "npc/comb_soldier/vo/designatetargetas.wav")
Schema.voices.Add("comb", "DISPLACE", "Displace", "npc/comb_soldier/vo/displace.wav")
Schema.voices.Add("comb", "ECHO", "Echo", "npc/comb_soldier/vo/echo.wav")
Schema.voices.Add("comb", "ENGAGED IN CLEAN UP", "Engaged in clean up", "npc/comb_soldier/vo/engagedincleanup.wav")
Schema.voices.Add("comb", "ENGAGING", "Engaging", "npc/comb_soldier/vo/engaging.wav")
Schema.voices.Add("comb", "EXECUTING FULL RESPONSE", "Executing full response", "npc/comb_soldier/vo/executingfullresponse.wav")
Schema.voices.Add("comb", "EXTRACTOR AWAY", "Extractor away", "npc/comb_soldier/vo/extractoraway.wav")
Schema.voices.Add("comb", "EXTRACTOR IS LIVE", "Extractor is live", "npc/comb_soldier/vo/extractorislive.wav")
Schema.voices.Add("comb", "FIST", "Fist", "npc/comb_soldier/vo/fist.wav")
Schema.voices.Add("comb", "FLARE DOWN", "Flare down", "npc/comb_soldier/vo/flaredown.wav")
Schema.voices.Add("comb", "FLASH", "Flash", "npc/comb_soldier/vo/flash.wav")
Schema.voices.Add("comb", "FLATLINE", "Flatline", "npc/comb_soldier/vo/flatline.wav")
Schema.voices.Add("comb", "Flat line", "Flatline", "npc/comb_soldier/vo/flatline.wav")
Schema.voices.Add("comb", "FLUSH", "Flush", "npc/comb_soldier/vo/flush.wav")
Schema.voices.Add("comb", "FULL ACTIVE", "Full active", "npc/comb_soldier/vo/fullactive.wav")
Schema.voices.Add("comb", "GHOST", "Ghost", "npc/comb_soldier/vo/ghost.wav")
Schema.voices.Add("comb", "GO SHARP", "Go sharp", "npc/comb_soldier/vo/gosharp.wav")
Schema.voices.Add("comb", "GO SHARP2", "Go sharp!, Go sharp!", "npc/comb_soldier/vo/gosharpgosharp.wav")
Schema.voices.Add("comb", "GRID", "GRID", "npc/comb_soldier/vo/grid.wav")
Schema.voices.Add("comb", "HAMMER", "HAMMER", "npc/comb_soldier/vo/hammer.wav")
Schema.voices.Add("comb", "HARDEN THAT POSITION", "Harden that position", "npc/comb_soldier/vo/hardenthatposition.wav")
Schema.voices.Add("comb", "HELIX", "HELIX", "npc/comb_soldier/vo/helix.wav")
Schema.voices.Add("comb", "HUNTER", "HUNTER", "npc/comb_soldier/vo/hunter.wav")
Schema.voices.Add("comb", "HURRICANE", "Hurricane", "npc/comb_soldier/vo/hurricane.wav")
Schema.voices.Add("comb", "ICE", "Ice", "npc/comb_soldier/vo/ice.wav")
Schema.voices.Add("comb", "INBOUND", "Inbound", "npc/comb_soldier/vo/inbound.wav")
Schema.voices.Add("comb", "INFECTED", "Infected", "npc/comb_soldier/vo/infected.wav")
Schema.voices.Add("comb", "ION", "Ion", "npc/comb_soldier/vo/ion.wav")
Schema.voices.Add("comb", "IS THAT CODE", "Is that code", "npc/comb_soldier/vo/isatcode.wav")
Schema.voices.Add("comb", "JET", "Jet", "npc/comb_soldier/vo/jet.wav")
Schema.voices.Add("comb", "JUDGE", "Judge", "npc/comb_soldier/vo/judge.wav")
Schema.voices.Add("comb", "KILO", "Kilo", "npc/comb_soldier/vo/kilo.wav")
Schema.voices.Add("comb", "LEADER", "LEADER", "npc/comb_soldier/vo/leader.wav")
Schema.voices.Add("comb", "LOST CONTACT", "Lost contact", "npc/comb_soldier/vo/lostcontact.wav")
Schema.voices.Add("comb", "MACE", "MACE", "npc/comb_soldier/vo/lostcontact.wav")
Schema.voices.Add("comb", "METERS", "Meters", "npc/comb_soldier/vo/meters.wav")
Schema.voices.Add("comb", "MOVE IN", "Move in", "npc/comb_soldier/vo/movein.wav")
Schema.voices.Add("comb", "NECROTICS INBOUND", "Necrotics inbound", "npc/comb_soldier/vo/necroticsinbound.wav")
Schema.voices.Add("comb", "NINER", "Niner", "npc/comb_soldier/vo/niner.wav")
Schema.voices.Add("comb", "NOMAD", "NOMAD", "npc/comb_soldier/vo/nomad.wav")
Schema.voices.Add("comb", "NOVA", "NOVA", "npc/comb_soldier/vo/nova.wav")
Schema.voices.Add("comb", "NO VISCON", "No viscon", "npc/comb_soldier/vo/noviscon.wav")
Schema.voices.Add("comb", "ONE CONTAINED", "One contained", "npc/comb_soldier/vo/onecontained.wav")
Schema.voices.Add("comb", "ONE DOWN", "One down", "npc/comb_soldier/vo/onedown.wav")
Schema.voices.Add("comb", "OVERWATCH", "Overwatch", "npc/comb_soldier/vo/overwatch.wav")
Schema.voices.Add("comb", "OVERWATCH REPORTS POSSIBLE HOSTILES INBOUND", "Overwatch reports possible hostiles inbound", "npc/comb_soldier/vo/overwatchreportspossiblehostiles.wav")
Schema.voices.Add("comb", "OVERWATCH REQUEST REINFORCEMENT", "Overwatch request reinforcement", "npc/comb_soldier/vo/overwatchrequestreinforcement.wav")
Schema.voices.Add("comb", "OVERWATCH REQUEST SKYSHIELD", "Overwatch request skysheild", "npc/comb_soldier/vo/overwatchrequestskyshield.wav")
Schema.voices.Add("comb", "OVERWATCH SECTOR OVERRUN", "Overwatch sector overrun, repeat sector overrun", "npc/comb_soldier/vo/overwatchsectoroverrun.wav")
Schema.voices.Add("comb", "OVERWATCH TARGET CONTAINED", "Overwatch target contained", "npc/comb_soldier/vo/overwatchtargetcontained.wav")
Schema.voices.Add("comb", "OVERWATCH TEAM IS DOWN", "Overwatch team is down sector is non control", "npc/comb_soldier/vo/overwatchteamisdown.wav")
Schema.voices.Add("comb", "PAYBACK", "Payback", "npc/comb_soldier/vo/payback.wav")
Schema.voices.Add("comb", "PHANTOM", "Phantom", "npc/comb_soldier/vo/phantom.wav")
Schema.voices.Add("comb", "PRIORITY ONE OBJECTIVE", "Priority one objective", "npc/comb_soldier/vo/priority1objective.wav")
Schema.voices.Add("comb", "QUICKSAND", "Quicksand", "npc/comb_soldier/vo/quicksand.wav")
Schema.voices.Add("comb", "RANGE", "Range", "npc/comb_soldier/vo/range.wav")
Schema.voices.Add("comb", "RANGER", "Ranger", "npc/comb_soldier/vo/ranger.wav")
Schema.voices.Add("comb", "RAZOR", "Razor", "npc/comb_soldier/vo/razor.wav")
Schema.voices.Add("comb", "READY CHARGES", "Ready charges", "npc/comb_soldier/vo/readycharges.wav")
Schema.voices.Add("comb", "READY EXTRACTORS", "Ready extractors", "npc/comb_soldier/vo/readyextractors.wav")
Schema.voices.Add("comb", "READY WEAPONS", "Ready weapons", "npc/comb_soldier/vo/readyweapons.wav")
Schema.voices.Add("comb", "REAPER", "Reaper", "npc/comb_soldier/vo/reaper.wav")
Schema.voices.Add("comb", "REPORT ALL POSTIONS CLEAR", "Report all positions clear", "npc/comb_soldier/vo/reportallpositionsclear.wav")
Schema.voices.Add("comb", "REPORTING CLEAR", "Reporting clear", "npc/comb_soldier/vo/reportingclear.wav")
Schema.voices.Add("comb", "REQUEST MEDICAL", "Request medical", "npc/comb_soldier/vo/requestmedical.wav")
Schema.voices.Add("comb", "RIPCORD", "Ripcord", "npc/comb_soldier/vo/ripcord.wav")
Schema.voices.Add("comb", "RIPCORD2", "Ripcord, Ripcord", "npc/comb_soldier/vo/ripcordripcord.wav")
Schema.voices.Add("comb", "SAVAGE", "Savage", "npc/comb_soldier/vo/savage.wav")
Schema.voices.Add("comb", "SCAR", "Scar", "npc/comb_soldier/vo/scar.wav")
Schema.voices.Add("comb", "SECTOR IS NOT SECURE", "Sector is not secure", "npc/comb_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("comb", "SECTOR IS SECURE", "Sector is secure no viscon", "npc/comb_soldier/vo/sectorissecurenovison.wav")
Schema.voices.Add("comb", "SECURE", "Secure", "npc/comb_soldier/vo/secure.wav")
Schema.voices.Add("comb", "SHADOW", "Shadow", "npc/comb_soldier/vo/shadow.wav")
Schema.voices.Add("comb", "SHARP ZONE", "Sharp zone", "npc/comb_soldier/vo/sharpzone.wav")
Schema.voices.Add("comb", "SIGHT OF LINE IS CLEAR", "Sight of line is clear", "npc/comb_soldier/vo/sightlineisclear.wav")
Schema.voices.Add("comb", "SLAM", "Slam", "npc/comb_soldier/vo/slam.wav")
Schema.voices.Add("comb", "SLASH", "Slash", "npc/comb_soldier/vo/slash.wav")
Schema.voices.Add("comb", "SPEAR", "Spear", "npc/comb_soldier/vo/spear.wav")
Schema.voices.Add("comb", "STAB", "Stab", "npc/comb_soldier/vo/stab.wav")
Schema.voices.Add("comb", "STABILZATION TEAM AT SECTOR CONTROL", "Stabilzation team at sector control", "npc/comb_soldier/vo/stabilizationteamhassector.wav")
Schema.voices.Add("comb", "STABILZATION TEAM HOLDING AT POSTION", "Stabilzation team holding at position", "npc/comb_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("comb", "STANDING BY", "Standing by", "npc/comb_soldier/vo/standingby].wav")
Schema.voices.Add("comb", "STAR", "Star", "npc/comb_soldier/vo/star.wav")
Schema.voices.Add("comb", "STAY ALERT", "Stay alert", "npc/comb_soldier/vo/stayalert.wav")
Schema.voices.Add("comb", "STAY ALERT REPORT SIGHT LINES", "Stay alert report sight lines" ,"npc/comb_soldier/vo/stayalertreportsightlines.wav")
Schema.voices.Add("comb", "STINGER", "Stinger", "npc/comb_soldier/vo/stinger.wav")
Schema.voices.Add("comb", "STORM", "Storm", "npc/comb_soldier/vo/storm.wav")
Schema.voices.Add("comb", "STRIKER", "Striker", "npc/comb_soldier/vo/striker.wav")
Schema.voices.Add("comb", "SUNDOWN", "Sundown", "npc/comb_soldier/vo/sundown.wav")
Schema.voices.Add("comb", "SUPPRESSING", "Suppressing", "npc/comb_soldier/vo/suppressing.wav")
Schema.voices.Add("comb", "SWARM OUT BREAK IN SECTOR", "Swarm out break in sector", "npc/comb_soldier/vo/swarmoutbreakinsector.wav")
Schema.voices.Add("comb", "SWEEPER", "Sweeper", "npc/comb_soldier/vo/sweeper.wav")
Schema.voices.Add("comb", "SWEEPING IN", "Sweeping in", "npc/comb_soldier/vo/sweepingin.wav")
Schema.voices.Add("comb", "SWIFT", "Swift", "npc/comb_soldier/vo/swift.wav")
Schema.voices.Add("comb", "SWORD", "Sword", "npc/comb_soldier/vo/sword.wav")
Schema.voices.Add("comb", "TARGET", "Target", "npc/comb_soldier/vo/target.wav")
Schema.voices.Add("comb", "TARGET COMPROMISED", "Target compromised move in, move in", "npc/comb_soldier/vo/targetcompromisedmovein.wav")
Schema.voices.Add("comb", "WARP UP", "Thats it warp up", "npc/comb_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("comb", "UNIFORM", "Uniform", "npc/comb_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("comb", "UNIT IS CLOSING", "Unit is closing", "npc/comb_soldier/vo/unitisclosing.wav")
Schema.voices.Add("comb", "UNIT IS INBOUND", "Unit is inbound", "npc/comb_soldier/vo/unitisinbound.wav")
Schema.voices.Add("comb", "VAMP", "Vamp", "npc/comb_soldier/vo/vamp.wav")
Schema.voices.Add("comb", "VISCON", "Viscon", "npc/comb_soldier/vo/viscon.wav")
Schema.voices.Add("comb", "VISUAL ON EXOGENS", "Visual on exogens", "npc/comb_soldier/vo/visualonexogens.wav")
Schema.voices.Add("comb", "WEAPONS OFF SAFE", "Weapons off safe prep for contact")
Schema.voices.Add("comb", "WE HAVE FREE PARASITES", "We have free parasites", "npc/comb_soldier/vo/wehavefreeparasites.wav")
Schema.voices.Add("comb", "WINDER", "Winder", "npc/comb_soldier/vo/winder.wav")

Schema.voices.AddClass("comb", function(client)
	return client:Team() == FACTION_OTA or client:Team() == FACTION_MPF end)